# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures
# for details
---
fixtures:
  forge_modules:
    alternatives: "puppet/alternatives"
    kmod: "camptocamp/kmod"
    stdlib: "puppetlabs/stdlib"
    ntp: "puppetlabs/ntp"
    auditd: "kemra102/auditd"
    # postfix: "camptocamp-postfix"
    logrotate: "puppet/logrotate"
    augeasproviders_shellvar: "herculesteam/augeasproviders_shellvar"
    augeasproviders_pam: "herculesteam/augeasproviders_pam"
    augeasproviders_grub: "herculesteam/augeasproviders_grub"
    augeasproviders_core: "herculesteam/augeasproviders_core"
    augeasproviders_sysctl: "herculesteam/augeasproviders_sysctl"
    firewall: "puppetlabs/firewall"
    augeas: "camptocamp/augeas"
    augeas_core: "puppetlabs/augeas_core"
    cron: "puppet/cron"
    mailalias_core: "puppetlabs/mailalias_core"
    reboot: "puppetlabs/reboot"
    mount: "puppetlabs/mount_core"
    chrony: "aboe/chrony"
  repositories:
    postfix:
      repo: "https://github.com/camptocamp/puppet-postfix.git"
      branch: "master"
