# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures
# for details
---
fixtures:
  forge_modules:
    alternatives: "puppet-alternatives"
    auditd: "kemra102-auditd"
    augeas: "camptocamp-augeas"
    augeas_core: "puppetlabs-augeas_core"
    augeasproviders_core: "herculesteam-augeasproviders_core"
    augeasproviders_grub: "herculesteam-augeasproviders_grub"
    augeasproviders_pam: "herculesteam-augeasproviders_pam"
    augeasproviders_shellvar: "herculesteam-augeasproviders_shellvar"
    augeasproviders_sysctl: "herculesteam-augeasproviders_sysctl"
    chrony: "aboe-chrony"
    cron: "puppet-cron"
    facts: "puppetlabs-facts"
    firewall: "puppetlabs-firewall"
    firewalld: 'puppet-firewalld'
    kmod: "camptocamp-kmod"
    logrotate: "puppet-logrotate"
    mailalias_core: "puppetlabs-mailalias_core"
    mount: "puppetlabs-mount_core"
    ntp: "puppetlabs-ntp"
    reboot: "puppetlabs-reboot"
    stdlib: "puppetlabs-stdlib"
    provision: "puppetlabs-provision"
    #postfix: "camptocamp-postfix"
  repositories:
    postfix:
      repo: "https://github.com/fervidus/puppet-postfix.git"
      branch: "master"
    puppet_agent: 'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'
    provision: 'https://github.com/puppetlabs/provision.git'
